### ISSUE TITLE
EdgeDNS not resolving the DNS Names

### ISSUE THREAD

**Issue by bitvijays** [kubeedge/kubeedge#2688]
Dear KubeEdge Team,

Hope you are doing well. Thank you for your awesome support 👍 Much appreciated. Could you please guide us on the below issue. Issue https://github.com/kubeedge/kubeedge/issues/2638 may also be referred to have more background.

Yours sincerely,
Vijay

**What happened**:

Edgecore DNS should resolve the DNS name of the services. There are multiple services running on the cloudcore

### On Cloudcore

```console
debian@cloudcore:~/$ kubectl get service -n my-kafka-project
NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
my-cluster2-edge-zookeeper-client   ClusterIP   10.96.210.214    <none>        2181/TCP                     37s
my-cluster2-edge-zookeeper-nodes    ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   37s
my-cluster2-kafka-bootstrap         ClusterIP   10.102.188.127   <none>        9091/TCP                     4d22h
my-cluster2-kafka-brokers           ClusterIP   None             <none>        9091/TCP                     4d22h
my-cluster2-kafka-plain-0           NodePort    10.110.123.112   <none>        9092:30135/TCP               4d22h
my-cluster2-kafka-plain-bootstrap   NodePort    10.97.17.104     <none>        9092:31525/TCP               4d22h
my-cluster2-kafka-tls-0             NodePort    10.103.84.253    <none>        9093:32000/TCP               4d22h
my-cluster2-kafka-tls-bootstrap     NodePort    10.105.146.0     <none>        9093:32100/TCP               4d22h
my-cluster2-zookeeper-client        ClusterIP   10.106.50.102    <none>        2181/TCP                     4d22h
my-cluster2-zookeeper-nodes         ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   4d22h
```

On cloudcore, DNS resolution works 

```console
debian@cloudcore:~/$ kubectl exec -i -t dnsutils -- nslookup my-cluster2-edge-zookeeper-nodes.my-kafka-project
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local
Address: 172.17.0.2
```

### On Edgecore Node (Worker Node)

```console
root@node-0101:~# ping my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local
PING my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local (9.251.0.5) 56(84) bytes of data.
^C
--- my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1020ms
```

`my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local` resolves to `9.251.0.5`. 

**What you expected to happen**:

`my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local` should resolve to `172.17.0.2`. 

**How to reproduce it (as minimally and precisely as possible)**:

- Create a KubeEdge master node
- Create a KubeEdge worker node
- Create a service on the Master, maybe follow [EdgeMesh](https://kubeedge.io/en/docs/advanced/edgemesh/)

**Anything else we need to know?**:

**Environment**:

- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

```console
cloudcore --version
KubeEdge v1.6.0
```

```console
edgecore --version
2021-03-22 16:13:26.427871 I | INFO: Install client plugin, protocol: rest
2021-03-22 16:13:26.428232 I | INFO: Installed service discovery plugin: edge
KubeEdge v1.6.0
```

### Edgecore log

```
Mar 22 15:30:44 node-0101.bitvijays.local edgecore[1690]: W0322 15:30:44.569314    1690 module.go:60] EdgeMesh Stop
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.515205    7996 listener.go:138] [EdgeMesh] get listener default.kubernetes from edge db: 9.251.0.2
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.529383    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-edge-zookeeper-client from edge db: 9.251.0.26
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.540395    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-kafka-tls-bootstrap from edge db: 9.251.0.22
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.551900    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-kafka-plain-bootstrap from edge db: 9.251.0.23
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.562639    7996 listener.go:138] [EdgeMesh] get listener kube-system.kubernetes-dashboard from edge db: 9.251.0.1
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.573244    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-kafka-brokers from edge db: 9.251.0.21
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.583961    7996 listener.go:138] [EdgeMesh] get listener nginx.nginx-svc from edge db: 9.251.0.17
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.595640    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-kafka-plain-0 from edge db: 9.251.0.24
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.606862    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-kafka-bootstrap from edge db: 9.251.0.20
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.618119    7996 listener.go:138] [EdgeMesh] get listener kube-system.kube-dns from edge db: 9.251.0.3
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.629357    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-kafka-tls-0 from edge db: 9.251.0.25
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.640260    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-zookeeper-client from edge db: 9.251.0.18
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.651845    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-zookeeper-nodes from edge db: 9.251.0.19
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.662448    7996 listener.go:138] [EdgeMesh] get listener default.nginx-svc from edge db: 9.251.0.8
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.673405    7996 listener.go:138] [EdgeMesh] get listener my-kafka-project.my-cluster2-edge-zookeeper-nodes from edge db: 9.251.0.27
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.789627    7996 proxy.go:95] [EdgeMesh] chain EDGE-MESH not exists
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.813634    7996 proxy.go:103] [EdgeMesh] inbound rule -p tcp -d 9.251.0.0/16 -i docker0 -j EDGE-MESH not exists
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.841650    7996 proxy.go:111] [EdgeMesh] outbound rule -p tcp -d 9.251.0.0/16 -o docker0 -j EDGE-MESH not exists
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: I0322 15:31:03.869669    7996 proxy.go:119] [EdgeMesh] dnat rule -p tcp -j DNAT --to-destination 172.17.0.1:40001 not exists
Mar 22 15:31:03 node-0101.bitvijays.local edgecore[7996]: W0322 15:31:03.870103    7996 proxy.go:64] [EdgeMesh] add route err: file exists
Mar 22 15:31:14 node-0101.bitvijays.local edgecore[7996]: E0322 15:31:14.430164    7996 dns.go:290] [EdgeMesh] service node-0101.bitvijays.local is not found in this cluster
Mar 22 15:31:14 node-0101.bitvijays.local edgecore[7996]: W0322 15:31:14.430239    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:31:14 node-0101.bitvijays.local edgecore[7996]: W0322 15:31:14.430319    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns



Mar 22 15:56:43 node-0101.bitvijays.local edgecore[7996]: I0322 15:56:43.255161    7996 listener.go:316] [EdgeMesh] insert services: 1 resource: my-kafka-project/service/my-cluster2-edge-zookeeper-client
Mar 22 15:56:43 node-0101.bitvijays.local edgecore[7996]: I0322 15:56:43.255312    7996 listener.go:323] [EdgeMesh] insert svc my-kafka-project.my-cluster2-edge-zookeeper-client into cache
Mar 22 15:56:43 node-0101.bitvijays.local edgecore[7996]: I0322 15:56:43.431086    7996 listener.go:341] [EdgeMesh] update podlist, resource: my-kafka-project/podlist/my-cluster2-edge-zookeeper-client
Mar 22 15:56:43 node-0101.bitvijays.local edgecore[7996]: I0322 15:56:43.439300    7996 listener.go:357] [EdgeMesh] insert/update pods my-kafka-project.my-cluster2-edge-zookeeper-client into cache
Mar 22 15:56:43 node-0101.bitvijays.local edgecore[7996]: I0322 15:56:43.443591    7996 listener.go:341] [EdgeMesh] update podlist, resource: my-kafka-project/podlist/my-cluster2-edge-zookeeper-nodes
Mar 22 15:56:43 node-0101.bitvijays.local edgecore[7996]: I0322 15:56:43.450331    7996 listener.go:357] [EdgeMesh] insert/update pods my-kafka-project.my-cluster2-edge-zookeeper-nodes into cache
Mar 22 15:56:43 node-0101.bitvijays.local edgecore[7996]: I0322 15:56:43.600018    7996 listener.go:316] [EdgeMesh] insert services: 1 resource: my-kafka-project/service/my-cluster2-edge-zookeeper-nodes
Mar 22 15:56:43 node-0101.bitvijays.local edgecore[7996]: I0322 15:56:43.600143    7996 listener.go:323] [EdgeMesh] insert svc my-kafka-project.my-cluster2-edge-zookeeper-nodes into cache
Mar 22 15:56:56 node-0101.bitvijays.local edgecore[7996]: E0322 15:56:56.335596    7996 dns.go:290] [EdgeMesh] service my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc is not found in this cluster
Mar 22 15:56:56 node-0101.bitvijays.local edgecore[7996]: W0322 15:56:56.335705    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:56:56 node-0101.bitvijays.local edgecore[7996]: E0322 15:56:56.351805    7996 dns.go:290] [EdgeMesh] service my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.lan is not found in this cluster
Mar 22 15:56:56 node-0101.bitvijays.local edgecore[7996]: W0322 15:56:56.351900    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:56:56 node-0101.bitvijays.local edgecore[7996]: E0322 15:56:56.731813    7996 dns.go:290] [EdgeMesh] service node-0101.bitvijays.local is not found in this cluster
Mar 22 15:56:56 node-0101.bitvijays.local edgecore[7996]: W0322 15:56:56.732555    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:56:56 node-0101.bitvijays.local edgecore[7996]: W0322 15:56:56.733379    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:57:04 node-0101.bitvijays.local edgecore[7996]: I0322 15:57:04.967691    7996 listener.go:341] [EdgeMesh] update podlist, resource: my-kafka-project/podlist/my-cluster2-edge-zookeeper-nodes
Mar 22 15:57:04 node-0101.bitvijays.local edgecore[7996]: I0322 15:57:04.976827    7996 listener.go:357] [EdgeMesh] insert/update pods my-kafka-project.my-cluster2-edge-zookeeper-nodes into cache
Mar 22 15:57:05 node-0101.bitvijays.local edgecore[7996]: I0322 15:57:05.436732    7996 listener.go:341] [EdgeMesh] update podlist, resource: my-kafka-project/podlist/my-cluster2-edge-zookeeper-client
Mar 22 15:57:05 node-0101.bitvijays.local edgecore[7996]: I0322 15:57:05.445713    7996 listener.go:357] [EdgeMesh] insert/update pods my-kafka-project.my-cluster2-edge-zookeeper-client into cache
Mar 22 15:57:05 node-0101.bitvijays.local edgecore[7996]: E0322 15:57:05.861076    7996 dns.go:290] [EdgeMesh] service node-0101.bitvijays.local is not found in this cluster
Mar 22 15:57:05 node-0101.bitvijays.local edgecore[7996]: W0322 15:57:05.861201    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:57:05 node-0101.bitvijays.local edgecore[7996]: W0322 15:57:05.861326    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:57:11 node-0101.bitvijays.local edgecore[7996]: E0322 15:57:11.545312    7996 dns.go:290] [EdgeMesh] service my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc is not found in this cluster
Mar 22 15:57:11 node-0101.bitvijays.local edgecore[7996]: W0322 15:57:11.546929    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:57:11 node-0101.bitvijays.local edgecore[7996]: E0322 15:57:11.562895    7996 dns.go:290] [EdgeMesh] service my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.lan is not found in this cluster
Mar 22 15:57:11 node-0101.bitvijays.local edgecore[7996]: W0322 15:57:11.562978    7996 dns.go:125] [EdgeMesh] failed to resolve dns: get from real dns
Mar 22 15:57:12 node-0101.bitvijays.local edgecore[7996]: E0322 15:57:12.753173    7996 dns.go:290] [EdgeMesh] service node-0101.bitvijays.local.lan is not found in this cluster
```

**Comment by Poorunga** [comment]
@bitvijays
At the KubeEdge edge nodes, the DNS server of edgemesh resolved the domain name request and returned a fake IP address in the 9.251.0.0/16 subnet, so  `my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local` resolves to `9.251.0.5`.

In the namespace of `my-kafka-project`, I don't see that you created a service named `my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes`. This may be the reason for the following mistakes:
```
...
Mar 22 15:57:11 node-0101.bitvijays.local edgecore[7996]: E0322 15:57:11.545312    7996 dns.go:290] [EdgeMesh] service my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc is not found in this cluster
...
```

**Comment by bitvijays** [comment]
Hi @Poorunga,

Hope you are doing well. Thank you for your support. 

- When we try to resolve `my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc` on the `cloudcore`, it gets resolved to `172.17.0.2`
- ` my-cluster2-edge-zookeeper-0` is a sub-domain of `my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local`. So, ideally should be resolved fine and should be resolved to `172.17.0.2`?

```
debian@cloudcore:~$ kubectl exec -i -t dnsutils -- nslookup my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   my-cluster2-edge-zookeeper-0.my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.local
Address: 172.17.0.2
```

#### Nginx example:

Following the tutorial of [Edge connection with EdgeMesh](https://kubeedge.io/en/docs/advanced/edgemesh/), deployed a nginx deployment on the edge.

```
debian@cloudcore:~$ kubectl get pods -o wide
NAME                                READY   STATUS    RESTARTS   AGE     IP            NODE                        NOMINATED NODE   READINESS GATES
dnsutils                            1/1     Running   58         7d14h   10.244.0.29   cloudcore                   <none>           <none>
nginx-deployment-77f96fbb65-8gbwv   1/1     Running   0          53s     172.17.0.3    node-0101.bitvijays.local   <none>           <none>
```

Which works fine when accessed from `node-0101` using `IPAddress`

```
ubuntu@node-0101:~$ curl 172.17.0.3
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
```

Created a service on the `cloudcore`

```
debian@cloudcore:~$kubectl get service -o wide
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)     AGE    SELECTOR
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP     18d    <none>
nginx-svc    ClusterIP   None         <none>        12345/TCP   6d6h   app=nginx
```

which resolves fine on `cloudcore`

```
debian@cloudcore:~$ kubectl exec -i -t dnsutils -- nslookup nginx-svc.default
Server:         10.96.0.10
Address:        10.96.0.10#53

Name:   nginx-svc.default.svc.cluster.local
Address: 172.17.0.3
```

However, when tried to resolve `nginx-svc.default.svc.cluster.local` on the edge node `node-0101`

```
ubuntu@node-0101:~$ ping nginx-svc.default.svc.cluster.local
PING nginx-svc.default.svc.cluster.local (9.251.0.8) 56(84) bytes of data.
From 172.17.0.1 (172.17.0.1) icmp_seq=1 Destination Host Unreachable
From 172.17.0.1 (172.17.0.1) icmp_seq=2 Destination Host Unreachable
From 172.17.0.1 (172.17.0.1) icmp_seq=3 Destination Host Unreachable
^C
--- nginx-svc.default.svc.cluster.local ping statistics ---
4 packets transmitted, 0 received, +3 errors, 100% packet loss, time 3061ms
```

Ideally `nginx-svc.default.svc.cluster.local` should resolve to `172.17.0.3` on the edge node. Right?

**Comment by Poorunga** [comment]
@bitvijays Unfortunately, now edgemesh cannot resolve sub-domain.

You're right. `nginx-svc.default.svc.cluster.local` should be resolved to `172.17.0.3` on the edge node. However, EdgeMesh currently uses a unique solution to achieve cluster ip and dns capabilities. This set of solutions may be discarded in the future, and a more cloud-native approach is adopted to implement clutser ip and dns on the edge.

**Comment by NickPyae** [comment]
same issue for. Deployed mysql pod and mysql-client connect to mysql. it's resolving to edgeMesh subnet 9.251.0.4 instead of docker0 subnet 172.17.0.4. What I ended up doing is I added hostAliases to mysql-client pod and it works. But it's a dirty trick @bitvijays

**Comment by bitvijays** [comment]
Hi @Poorunga @kevin-wangzefeng @Abirdcfly ,

We did tried to setup the KubeProxy + CNI as suggested in https://github.com/kubeedge/kubeedge/issues/2677 . However, we are still unable to perform the DNS resolutions. Is there a way to debug this somehow?

```
root@node-0101:/opt/cni/bin# ping my-cluster2-edge-zookeeper-nodes.my-kafka-project
ping: my-cluster2-edge-zookeeper-nodes.my-kafka-project: Name or service not known

root@node-0101:/opt/cni/bin# ping my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc
ping: my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc: Name or service not known

root@node-0101:/opt/cni/bin# ping my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.info
PING my-cluster2-edge-zookeeper-nodes.my-kafka-project.svc.cluster.info (185.53.177.53) 56(84) bytes of data.
185.53.177.53 -- is wrong.. probably coming from internet DNS
```

### What we tried

Our flannel at the edge Daemonset is working `kube-flannel-ds-edge-2dsj8`

```
debian@cloudcore:~$ kubectl get pods -n kube-system -o wide
NAME                                    READY   STATUS    RESTARTS   AGE     IP              NODE                        NOMINATED NODE   READINESS GATES
coredns-74f5c9f46c-5nbd5                1/1     Running   2          6d13h   10.244.0.26     cloudcore                   <none>           <none>
coredns-74f5c9f46c-h5vx9                1/1     Running   2          6d13h   10.244.0.25     cloudcore                   <none>           <none>
kube-apiserver-cloudcore                1/1     Running   16         19d     192.168.1.219   cloudcore                   <none>           <none>
kube-controller-manager-cloudcore       1/1     Running   16         19d     192.168.1.219   cloudcore                   <none>           <none>
kube-flannel-ds-4wsf2                   1/1     Running   0          78m     192.168.1.219   cloudcore                   <none>           <none>
kube-flannel-ds-edge-2dsj8              1/1     Running   7          40m     192.168.1.207   node-0101.bitvijays.local   <none>           <none>
kube-proxy-55l5v                        1/1     Running   0          115m    192.168.1.219   cloudcore                   <none>           <none>
kube-proxy-sc2kx                        1/1     Running   0          116m    192.168.1.207   node-0101.bitvijays.local   <none>           <none>
```

This could probably be verified by `port 10550 is listening`
```
root@node-0101:/opt/cni/bin# netstat -ltpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:30135           0.0.0.0:*               LISTEN      295243/kube-proxy
tcp        0      0 0.0.0.0:32000           0.0.0.0:*               LISTEN      295243/kube-proxy
tcp        0      0 0.0.0.0:32100           0.0.0.0:*               LISTEN      295243/kube-proxy
tcp        0      0 0.0.0.0:31525           0.0.0.0:*               LISTEN      295243/kube-proxy
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      295243/kube-proxy
tcp        0      0 127.0.0.1:10350         0.0.0.0:*               LISTEN      313664/edgecore
tcp        0      0 127.0.0.1:36721         0.0.0.0:*               LISTEN      313664/edgecore
tcp        0      0 127.0.0.1:40721         0.0.0.0:*               LISTEN      1974/containerd
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1654/systemd-resolv
tcp        0      0 127.0.0.1:10550         0.0.0.0:*               LISTEN      313664/edgecore
tcp6       0      0 :::10256                :::*                    LISTEN      295243/kube-proxy
```

Enabled dynamic controller in `cloudcore.yaml`

```
# vim /etc/kubeedge/config/cloudcore.yaml
modules:
  ..
  dynamicController:
    enable: true
```

Disabled EdgeMesh, setup up ClusterDNS/domain in `edgecore.yaml`

```
  edgeMesh:
    enable: false


    clusterDNS: "10.96.0.10"
    clusterDomain: "cluster.local"
    cniBinDir: /opt/cni/bin
    networkPluginName: cni

  metaManager:
    contextSendGroup: hub
    contextSendModule: websocket
    enable: true
    metaServer:
      enable: true
```

Edgecore logs

```
Mar 24 05:01:58 node-0101.bitvijays.local edgecore[313664]: E0324 05:01:58.384437  313664 watcher.go:215] failed to sync with latest state: the server could not find the requested resource
```

**Comment by kevin-wangzefeng** [comment]
Kubernetes doesn't support ping on services, you may try spining up a pod with nslookup inside, and execute nslookup inside the container

**Comment by kevin-wangzefeng** [comment]
Or you can simple try with curl
